export const menu = [
  {
    id: 1,
    name: "Margherita Pizza",
    rating: 4.5,
    price: 399,
    image: "/images/margherita-pizza.jpg",
    category: "pizza",
  },
  {
    id: 2,
    name: "Chicken Biryani",
    rating: 4.7,
    price: 299,
    image: "/images/chicken-biryani.jpg",
    category: "biryani",
  },
  {
    id: 3,
    name: "Sushi Platter",
    rating: 4.3,
    price: 599,
    image: "/images/sushi-platter.jpg",
    category: "starters",
  },
  {
    id: 4,
    name: "Caesar Salad",
    rating: 4.1,
    price: 199,
    image: "/images/caesar-salad.jpg",
    category: "starters",
  },
  {
    id: 5,
    name: "BBQ Chicken Wings",
    rating: 4.6,
    price: 249,
    image: "/images/bbq-chicken-wings.jpg",
    category: "starters",
  },
  {
    id: 6,
    name: "Pad Thai",
    rating: 4.4,
    price: 349,
    image: "/images/pad-thai.jpg",
    category: "main",
  },
  {
    id: 7,
    name: "Tacos",
    rating: 4.5,
    price: 199,
    image: "/images/tacos.jpg",
    category: "starters",
  },
  {
    id: 8,
    name: "Butter Chicken",
    rating: 4.8,
    price: 399,
    image: "/images/butter-chicken.jpg",
    category: "main",
  },
  {
    id: 9,
    name: "Chocolate Lava Cake",
    rating: 4.9,
    price: 149,
    image: "/images/chocolate-lava-cake.jpg",
    category: "dessert",
  },
  {
    id: 10,
    name: "Fish and Chips",
    rating: 4.2,
    price: 299,
    image: "/images/fish-and-chips.jpg",
    category: "starters",
  },
];
